[sources.pg_replication.credentials]
drivername = "postgres" # please set me up!
database = "postgres" # please set me up!
password = "postgres" # please set me up!
username = "postgres" # please set me up!
host = "host" # please set me up!
port = 5432  # please set me up!

[destination.filesystem]
bucket_url = "s3://demo/" # please set me up!

[destination.filesystem.credentials]
aws_access_key_id = "minio" # please set me up!
aws_secret_access_key = "minio123" # please set me up!
endpoint_url="http://localhost:9000/"
